version: "3.10"

services:

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  app: &django_conf
    build:
      context: ./app
    command: python manage.py runserver 0.0.0.0:80
    platform: linux/x86_64
    depends_on:
      - redis
    environment: &django_env
      ALLOWED_HOSTS: "*"
      BROKER_URI: "redis://redis:6379/0"

      POSTGRES_HOST: db.utlnolxqnjbcugdobvpu.supabase.co
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jklol13qwe@
      POSTGRES_PORT: 5432
      

      DEBUG: 1
      DISABLE_USER_METRICS: 1
      DOMAIN: "localhost:3000"
      REDIS_URI: "redis://redis:6379/1"

      OAUTH2_ID_HOST: "https://id-stage.samoletgroup.ru"

      SOCIAL_AUTH_SAMOLET_KEY: "PGLE09hd8xCyIU8V2BQMN42TwwkTvyvB8NdjWks2"
      SOCIAL_AUTH_SAMOLET_SECRET: "HEETCoQC3H68JumvchqFS0PkrtTPn0m3yr2Vt0csqLj7ICzSMRamS1hdl3xkdasKocq2PsRS80Mdkb7TzJWZGcUSrfrq9CZUvlvqWmDNvzpqmtZrl76phMnIfhsRK7JE"

    volumes:
      - ./app:/app
      - ./files:/files
    ports:
      - "8000:80"



  celery:
    <<: *django_conf
    command: celery -A dobriki worker -E -l DEBUG -Q celery,doc_constructor
    ports: [ ]

  celery_beat:
    <<: *django_conf
    command: celery -A dobriki beat -l DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
    ports: [ ]

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: search
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - search_net
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - search_data:/usr/share/elasticsearch/data

  fusionauth:
      image: fusionauth/fusionauth-app:latest
      depends_on:
        search:
          condition: service_healthy
      environment:
        <<: *django_env
        DATABASE_URL: jdbc:postgresql://db.utlnolxqnjbcugdobvpu.supabase.co:5432/postgres?user=postgres&password=jklol13qwe@
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: jklol13qwe@
        
        FUSIONAUTH_APP_RUNTIME_MODE: development
        FUSIONAUTH_APP_MEMORY: 512M
        SEARCH_SERVERS: http://search:9200
        SEARCH_TYPE: elasticsearch
      
      networks:
        - search_net
        - mailcatcher_net
      restart: unless-stopped
      ports:
        - 9011:9011
      volumes:
        - fusionauth_config:/usr/local/fusionauth/config


  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - mailcatcher_net

networks:
  search_net:
    driver: bridge
  mailcatcher_net:
    driver: bridge

volumes:
  fusionauth_config:
  search_data:
  redis: {}