import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";

import { Navbar } from "@/widgets/navbar";
import { cn } from "@/shared/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <Providers>
        <body className={cn("pb-16", inter.className)}>
          {children}
          <Navbar />
        </body>
      </Providers>
    </html>
  );
}
