import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './providers'

import { LoginButton } from '@/features/loginButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <Providers>
        <body className={inter.className}>
          <header>
            <LoginButton></LoginButton>
          </header>
          {children}
        </body>
      </Providers>
    </html>
  )
}
