import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";

import { cn } from "@/shared/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <Providers>
        <body className={cn("pb-16", inter.className)}>
          {children}
          <div className="h-[100vh] w-[100vw] bg-black fixed top-0 left-0 z-[99999] overflow-hidden device-hidden">
            сорямба ток мобильная версия
          </div>
        </body>
      </Providers>
    </html>
  );
}
