/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Achievement
 */
export interface Achievement {
    /**
     * 
     * @type {number}
     * @memberof Achievement
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Achievement
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Achievement
     */
    'description': string;
    /**
     * Минимальное значение (например, минуты тренировки или километры пробега)
     * @type {number}
     * @memberof Achievement
     */
    'target_value': number;
    /**
     * 
     * @type {Set<number>}
     * @memberof Achievement
     */
    'users'?: Set<number>;
}

