/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActivitySnapshot
 */
export interface ActivitySnapshot {
    /**
     * 
     * @type {number}
     * @memberof ActivitySnapshot
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof ActivitySnapshot
     */
    'step_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivitySnapshot
     */
    'distance': string;
    /**
     * 
     * @type {number}
     * @memberof ActivitySnapshot
     */
    'time': number;
    /**
     * 
     * @type {number}
     * @memberof ActivitySnapshot
     */
    'found': number;
    /**
     * 
     * @type {string}
     * @memberof ActivitySnapshot
     */
    'kcal': string;
    /**
     * 
     * @type {string}
     * @memberof ActivitySnapshot
     */
    'created_at'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ActivitySnapshot
     */
    'activity_type': number;
}

