/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    'type': ActivityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    'description'?: string | null;
}

export const ActivityTypeEnum = {
    Step: 'STEP',
    Ski: 'SKI',
    Running: 'RUNNING',
    Bycycle: 'BYCYCLE',
    Found: 'FOUND'
} as const;

export type ActivityTypeEnum = typeof ActivityTypeEnum[keyof typeof ActivityTypeEnum];


