/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ArticleAuthor
 */
export interface ArticleAuthor {
    /**
     * 
     * @type {number}
     * @memberof ArticleAuthor
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleAuthor
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleAuthor
     */
    'last_login'?: string | null;
    /**
     * Designates that this user has all permissions without explicitly assigning them.
     * @type {boolean}
     * @memberof ArticleAuthor
     */
    'is_superuser'?: boolean;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof ArticleAuthor
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleAuthor
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleAuthor
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleAuthor
     */
    'email'?: string;
    /**
     * Designates whether the user can log into this admin site.
     * @type {boolean}
     * @memberof ArticleAuthor
     */
    'is_staff'?: boolean;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     * @type {boolean}
     * @memberof ArticleAuthor
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ArticleAuthor
     */
    'date_joined'?: string;
    /**
     * The groups this user belongs to. A user will get all permissions granted to each of their groups.
     * @type {Set<number>}
     * @memberof ArticleAuthor
     */
    'groups'?: Set<number>;
    /**
     * Specific permissions for this user.
     * @type {Set<number>}
     * @memberof ArticleAuthor
     */
    'user_permissions'?: Set<number>;
}

