/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ArticleCategory
 */
export interface ArticleCategory {
    /**
     * 
     * @type {number}
     * @memberof ArticleCategory
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategory
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategory
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategory
     */
    'created_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCategory
     */
    'description': string;
}

