/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ArticleAuthor } from './article-author';
// May contain unused imports in some cases
// @ts-ignore
import { ArticleCategoryPreview } from './article-category-preview';
// May contain unused imports in some cases
// @ts-ignore
import { ArticleTag } from './article-tag';

/**
 * 
 * @export
 * @interface ArticlePreview
 */
export interface ArticlePreview {
    /**
     * 
     * @type {number}
     * @memberof ArticlePreview
     */
    'id'?: number;
    /**
     * 
     * @type {ArticleCategoryPreview}
     * @memberof ArticlePreview
     */
    'category'?: ArticleCategoryPreview;
    /**
     * 
     * @type {Array<ArticleTag>}
     * @memberof ArticlePreview
     */
    'tags'?: Array<ArticleTag>;
    /**
     * 
     * @type {string}
     * @memberof ArticlePreview
     */
    'likes'?: string;
    /**
     * 
     * @type {ArticleAuthor}
     * @memberof ArticlePreview
     */
    'author': ArticleAuthor;
    /**
     * 
     * @type {string}
     * @memberof ArticlePreview
     */
    'preview_text': string;
    /**
     * 
     * @type {string}
     * @memberof ArticlePreview
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ArticlePreview
     */
    'created_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlePreview
     */
    'last_updated_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlePreview
     */
    'image'?: string | null;
}

