/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ArticlePreview } from './article-preview';

/**
 * 
 * @export
 * @interface FeedArticlesList200Response
 */
export interface FeedArticlesList200Response {
    /**
     * 
     * @type {number}
     * @memberof FeedArticlesList200Response
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof FeedArticlesList200Response
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedArticlesList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<ArticlePreview>}
     * @memberof FeedArticlesList200Response
     */
    'results': Array<ArticlePreview>;
}

