/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Register
 */
export interface Register {
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    'password1': string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    'password2': string;
}

