/* tslint:disable */
/* eslint-disable */
/**
 * Dobriki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Member } from './member';

/**
 * 
 * @export
 * @interface UserTeam
 */
export interface UserTeam {
    /**
     * 
     * @type {number}
     * @memberof UserTeam
     */
    'id'?: number;
    /**
     * 
     * @type {Array<Member>}
     * @memberof UserTeam
     */
    'members'?: Array<Member>;
    /**
     * 
     * @type {string}
     * @memberof UserTeam
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserTeam
     */
    'description': string;
}

